# Airflow version to be installed
airflow_version: "2.7.3"

# Python version for the project
python_version: "3.9.18"

# Path to a virtual evn
mode:
  virtualenv:
    venv_path: "/Users/ita/github-classroom/FTDS-assignment-bay/p2-ftds024-rmt-m3-dwitawin/airflow/my_airflow_project/.venv"

# Airflow connections
connections:
    # Example connection
    # - conn_id: example
    #   conn_type: http
    #   host: http://example.com
    #   port: 80
    #   login: user
    #   password: pass
    #   schema: http
    #   extra:
    #      example_extra_field: example-value

# Airflow variables
variables:
    # Example variable
    # - key: example
    #   value: example-value
    #   description: example-description